# Site settings
title: Md adnanul Chowdhur
description: Md adnanul Chowdhury's web developer portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Md adnanul Chowdhury
user_description: I am Md adnanul Chowdhury, a web developer with experience in front-end and back-end technologies. I come from a Mechanical Engineering background with concentration in robotics. When I am not coding, I work as a full-time Uber driver in Big Apple, and ponder about the expansion of the universe.
user_title: Software Developer
email: adnanul1993@gmail.com
twitter_username: adnanulchowdhury
github_username:  adnanulchowdhury
gplus_username:  adnanulchowdhury

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
